//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTopping
    {
        public int IdHoaDonTopping { get; set; }
        public int IdTopping { get; set; }
        public string NameTopping { get; set; }
        public decimal GiaTopping { get; set; }
        public int IdChiTietHoaDon { get; set; }
    
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
    }
}
