//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int IdHoaDon { get; set; }
        public int IdNhanVien { get; set; }
        public Nullable<int> IdKhachHang { get; set; }
        public Nullable<int> IdBan { get; set; }
        public System.DateTime NgayMua { get; set; }
        public decimal TienNhan { get; set; }
        public Nullable<int> IdVoucher { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<decimal> Thue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual QLBan QLBan { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
